version: '3.7'

services:
  client:
    container_name: manegement-equipment-client
    image: node
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    command: "sleep infinity & npm i"
  
  server:
    container_name: manegement-equipment-server
    image: node
    ports:
        - 5000:5000
    volumes:
        - ./server:/app
    command: "sleep infinity & npm i"