version: '3.7'

services:
  client:
    container_name: manegement-equipment-client
    image: node
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    command: sh -c "(curl -sL https://netfree.link/dl/unix-ca.sh | sh ) && export NODE_EXTRA_CA_CERTS=/etc/ca-bundle.crt && npm i && sleep infinity"
  
  server:
    container_name: manegement-equipment-server
    image: node
    ports:
        - 5000:5000
    volumes:
        - ./server:/app
    command: sh -c "(curl -sL https://netfree.link/dl/unix-ca.sh | sh ) && export NODE_EXTRA_CA_CERTS=/etc/ca-bundle.crt && npm i && sleep infinity"